
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 26 14:05:46 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 50;
  public static final int CONST = 6;
  public static final int YIELD = 31;
  public static final int LRECT = 9;
  public static final int MINUS_MINUS = 46;
  public static final int NOT_EQUAL = 36;
  public static final int CASE = 21;
  public static final int LPAREN = 14;
  public static final int SEMI = 7;
  public static final int CONTINUE = 23;
  public static final int MINUS = 30;
  public static final int RPAREN = 15;
  public static final int GT_EQUAL = 38;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 51;
  public static final int COMMA = 5;
  public static final int CLASS = 11;
  public static final int DIV = 43;
  public static final int PLUS = 41;
  public static final int IF = 16;
  public static final int DOT = 33;
  public static final int LE = 39;
  public static final int RRECT = 10;
  public static final int EOF = 0;
  public static final int PLUS_PLUS = 45;
  public static final int RETURN = 24;
  public static final int EQUAL = 34;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int DOUBLE_EQUAL = 35;
  public static final int NUMBER = 49;
  public static final int MOD = 44;
  public static final int IDENT = 48;
  public static final int BREAK = 22;
  public static final int VOID = 13;
  public static final int SWITCH = 20;
  public static final int LE_EQUAL = 40;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int ENUM = 8;
  public static final int READ = 25;
  public static final int DOUBLE_COLON = 27;
  public static final int WHILE = 19;
  public static final int DEFAULT = 47;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int GT = 37;
  public static final int PRINT = 26;
  public static final int DO = 18;
}

